name: Publish to CocoaPods

on:
  workflow_dispatch:
    inputs:
      cocoapods_trunk_token:
        description: 'CocoaPods Trunk Token'
        required: true
        type: string

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Hide sensitive inputs
        uses: levibostian/action-hide-sensitive-inputs@v1

      - name: Set token to environment
        run: echo "COCOAPODS_TRUNK_TOKEN=${{ inputs.cocoapods_trunk_token }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Publish to CocoaPods Trunk
        run: pod trunk push PhoneNumberKit.podspec --allow-warnings
